/* HEADER FILE GENERATED BY snack VERSION 0.9.2 */
/* THIS FILE:  /home/yifan/test/Hetero-Mark/src/hsa/sw_hsa/kernels.h  */
/* INPUT FILE: /home/yifan/test/Hetero-Mark/src/hsa/sw_hsa/kernels.cl  */
#ifdef __cplusplus
#define _CPPSTRING_ "C" 
#endif
#ifndef __cplusplus
#define _CPPSTRING_ 
#endif
#ifndef __SNK_DEFS
#define SNK_MAX_STREAMS 8 
extern _CPPSTRING_ void stream_sync(const int stream_num);

#define SNK_ORDERED 1
#define SNK_UNORDERED 0

#include <stdint.h>
#ifndef HSA_RUNTIME_INC_HSA_H_
typedef struct hsa_signal_s { uint64_t handle; } hsa_signal_t;
#endif

typedef struct snk_task_s snk_task_t;
struct snk_task_s { 
   hsa_signal_t signal ; 
   snk_task_t* next;
};

typedef struct snk_lparm_s snk_lparm_t;
struct snk_lparm_s { 
   int ndim;                  /* default = 1 */
   size_t gdims[3];           /* NUMBER OF THREADS TO EXECUTE MUST BE SPECIFIED */ 
   size_t ldims[3];           /* Default = {64} , e.g. 1 of 8 CU on Kaveri */
   int stream;                /* default = -1 , synchrnous */
   int barrier;               /* default = SNK_UNORDERED */
   int acquire_fence_scope;   /* default = 2 */
   int release_fence_scope;   /* default = 2 */
} ;

/* This string macro is used to declare launch parameters set default values  */
#define SNK_INIT_LPARM(X,Y) snk_lparm_t * X ; snk_lparm_t  _ ## X ={.ndim=1,.gdims={Y},.ldims={64},.stream=-1,.barrier=SNK_UNORDERED,.acquire_fence_scope=2,.release_fence_scope=2} ; X = &_ ## X ;
 
/* Equivalent host data types for kernel data types */
typedef struct snk_image3d_s snk_image3d_t;
struct snk_image3d_s { 
   unsigned int channel_order; 
   unsigned int channel_data_type; 
   size_t width, height, depth;
   size_t row_pitch, slice_pitch;
   size_t element_size;
   void *data;
};

#define __SNK_DEFS
#endif
extern _CPPSTRING_ void sw_init_psi_p(const double a,const double di,const double dj,const double pcf,const unsigned M_LEN,const unsigned N_LEN,double* p,double* psi, const snk_lparm_t * lparm);
extern _CPPSTRING_ void sw_init_psi_p_init(const int printStats);
extern _CPPSTRING_ void sw_init_velocities(const double dx,const double dy,const unsigned M,const unsigned N,const double* psi,double* u,double* v, const snk_lparm_t * lparm);
extern _CPPSTRING_ void sw_init_velocities_init(const int printStats);
extern _CPPSTRING_ void sw_compute0(const double fsdx,const double fsdy,const unsigned M_LEN,const double* u,const double* v,const double* p,double* cu,double* cv,double* z,double* h, const snk_lparm_t * lparm);
extern _CPPSTRING_ void sw_compute0_init(const int printStats);
extern _CPPSTRING_ void sw_update0(const unsigned M,const unsigned N,const unsigned M_LEN,double* cu,double* cv,double* z,double* h, const snk_lparm_t * lparm);
extern _CPPSTRING_ void sw_update0_init(const int printStats);
extern _CPPSTRING_ void sw_compute1(const double tdts8,const double tdtsdx,const double tdtsdy,const unsigned M_LEN,const double* cu,const double* cv,const double* z,const double* h,const double* u_curr,const double* v_curr,const double* p_curr,double* u_next,double* v_next,double* p_next, const snk_lparm_t * lparm);
extern _CPPSTRING_ void sw_compute1_init(const int printStats);
extern _CPPSTRING_ void sw_update1(const unsigned M,const unsigned N,const unsigned M_LEN,double* u_next,double* v_next,double* p_next, const snk_lparm_t * lparm);
extern _CPPSTRING_ void sw_update1_init(const int printStats);
extern _CPPSTRING_ void sw_time_smooth(const unsigned M,const unsigned N,const unsigned M_LEN,const double alpha,double* u,double* v,double* p,double* u_curr,double* v_curr,double* p_curr,double* u_next,double* v_next,double* p_next, const snk_lparm_t * lparm);
extern _CPPSTRING_ void sw_time_smooth_init(const int printStats);
